apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-03T15:23:50Z"
  generation: 1
  labels:
    app: fd-api
  name: fd-api
  namespace: default
  resourceVersion: "19984662"
  uid: 60fb55dd-a107-48eb-8d96-b2f48a264575
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fd-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fd-api
    spec:
      containers:
      - image: lukbast/fd_api:2022.2.1.RELEASE
        imagePullPolicy: IfNotPresent
        name: fd-api-nwxgn
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-03T15:23:50Z"
    lastUpdateTime: "2022-02-03T15:24:25Z"
    message: ReplicaSet "fd-api-78675fcdcf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-03-14T16:00:02Z"
    lastUpdateTime: "2022-03-14T16:00:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-02-03T15:24:59Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: fd-api
  name: fd-api
  namespace: default
  resourceVersion: "49181"
  uid: e6c39e09-b0e5-4421-93a7-d2ac63cf877d
spec:
  clusterIP: 10.32.1.24
  clusterIPs:
  - 10.32.1.24
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32678
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: fd-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.68.160.234
